server:
  port: 8081
spring:
  cloud: 
    config:
      server: 
        git:
          default_label: main
          uri: https://github.com/DiegoSilva996/configServer3-Project.git
          search-paths: config-data
  application:
    name: config-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
